language: node_js
sudo: false
cache: yarn
node_js:
- '6.1'
env: CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_d7758aef558b_key -iv $encrypted_d7758aef558b_iv
  -in test.json.enc -out ./config/test.json -d
- openssl aes-256-cbc -K $encrypted_d7758aef558b_key -iv $encrypted_d7758aef558b_iv
  -in default.json.enc -out ./config/default.json -d