language: node_js
sudo: false
cache: yarn
node_js:
- '6.1'
env: CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_17894d9e3b36_key -iv $encrypted_17894d9e3b36_iv
  -in test.json.enc -out ./test.json -d
- openssl aes-256-cbc -K $encrypted_17894d9e3b36_key -iv $encrypted_17894d9e3b36_iv
  -in default.json.enc -out ./default.json -d
